apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate.fullname" . }}-env
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:

  {{- if not (hasKey .Values.renovate "env") -}}
  {{- $_ := set .Values "env" dict -}}
  {{- end -}}

  {{- if not (hasKey .Values.renovate.env "RENOVATE_CONFIG_FILE") -}}
  {{- $configFile := printf "/usr/src/app/config.%s" .Values.renovate.appConfig.extension -}}
  {{- $_ := set .Values.renovate.env "RENOVATE_CONFIG_FILE" $configFile -}}
  {{- end -}}

  {{/* SETUP CONFIG */}}
  {{ range $key, $value := .Values.renovate.env }}
  {{ upper $key}}: {{ quote $value }}
  {{ end }}